default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Root@12345
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: todo_app_development

test:
  <<: *default
  database: todo_app_test

production:
  primary: &primary_production
    <<: *default
    database: todo_app_production
    username: todo_app
    password: <%= ENV["TODO_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: todo_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: todo_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: todo_app_production_cable
    migrations_paths: db/cable_migrate
